namespace: marcwrobel
name: assertions
description: A reusable collection of assertions for Ansible.
version: 1.0.0
license: [ 'MIT' ]

readme: README.md
authors: [ 'Marc Wrobel (https://www.marcwrobel.fr/)' ]

dependencies: { }

tags: [ 'ansible', 'testing' ]

repository: https://github.com/marcwrobel/ansible-collection-assertions
documentation: https://github.com/marcwrobel/ansible-collection-assertions
homepage: https://github.com/marcwrobel/ansible-collection-assertions
issues: https://github.com/marcwrobel/ansible-collection-assertions/issues

build_ignore: [ 'molecule' ]
