---
- name: 'Converge'
  hosts: 'all'
  collections:
    - 'marcwrobel.assertions'
  tasks:
    - name: 'Create test file for assert_file_content'
      copy:
        dest: '/tmp/test'
        mode: '0644'
        content: |
          line1
          line2
          line3
