---

- name: 'Path assertion are properly re-routed to assert_that_path (1)'
  include_role:
    name: 'assert_that_file'
  vars:
    with_path: '/etc/passwd'
    exists: true
    has_mode: '0644'
    has_owner: 'root'
    has_group: 'root'

- name: 'Path assertion are properly re-routed to assert_that_path (2)'
  include_role:
    name: 'assert_that_file'
  vars:
    with_path: '/does/not/exists'
    exists: false

- name: 'When file content match the given case-sensitive regex, then succeeds'
  include_role:
    name: 'assert_that_file'
  vars:
    with_path: '/tmp/test'
    has_content_matching: '^# Ansible managed'
    using_ignorecase_for_content_matching: false

- name: 'When file content match the given case-insensitive regex, then succeeds'
  include_role:
    name: 'assert_that_file'
  vars:
    with_path: '/tmp/test'
    has_content_matching: '^LINE3$'

- name: 'When file content match the given global regex, then succeeds'
  include_role:
    name: 'assert_that_file'
  vars:
    with_path: '/tmp/test'
    has_content_matching: 'line1\n.+\nline3'
    using_multiline_for_content_matching: false

- name: 'When file content does not match the given regex, then fails'
  block:
    - name: 'Assertion'
      include_role:
        name: 'assert_that_file'
        apply:
          ignore_errors: true
      vars:
        with_path: '/tmp/test'
        has_content_matching: '^LINE3$'
        using_ignorecase_for_content_matching: false
    - name: 'Verification'
      assert:
        that:
          - 'assert_that_file__has_content_matching_assertion is failed'
          - 'assert_that_file__has_content_matching_assertion.msg == "/tmp/test content does not match \"^LINE3$\" (multi-line=True, ignore-case=False)."'
        fail_msg: 'assertion result : {{ assert_that_file__has_content_matching_assertion | to_json }}'
