---

- name: 'When file content match the given case-sensitive regex, then succeeds'
  include_role:
    name: 'assert_file_content'
  vars:
    path: '/tmp/test'
    match: '^line2$'
    ignorecase: false

- name: 'When file content match the given case-insensitive regex, then succeeds'
  include_role:
    name: 'assert_file_content'
  vars:
    path: '/tmp/test'
    match: '^LINE3$'

- name: 'When file content match the given global regex, then succeeds'
  include_role:
    name: 'assert_file_content'
  vars:
    path: '/tmp/test'
    match: 'line1\n.+\nline3'
    multiline: false

- name: 'When file content does not match the given regex, then fails'
  block:
    - name: 'Assertion'
      include_role:
        name: 'assert_file_content'
        apply:
          ignore_errors: true
      vars:
        path: '/tmp/test'
        match: '^LINE3$'
        ignorecase: false
    - name: 'Verification'
      assert:
        that:
          - 'assert_file_content__match_assertion is failed'
          - 'assert_file_content__match_assertion.msg == "/tmp/test content does not match \"^LINE3$\" (multi-line=True, ignore-case=False)."'
        fail_msg: 'assertion result : {{ assert_file_content__match_assertion | to_json }}'
