---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  collections:
    - 'marcwrobel.assertions'
  tasks:
    - include_tasks: 'verify-ansible-version.yml'
    - include_tasks: 'verify-path.yml'
