---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  collections:
    - 'marcwrobel.assertions'
  tasks:
    - include_tasks: 'verify-assert_file_content.yml'
    - include_tasks: 'verify-assert_path.yml'
    - include_tasks: 'verify-assert_ansible_version.yml'
