---

- name: 'Clear assert_* variables'
  set_fact:
    assert_file_content__path_defined_assertion:
    assert_file_content__match_defined_assertion:
    assert_file_content__path_file_assertion:
    assert_file_content__match_assertion:

- name: "Assert that path variable is defined"
  assert:
    that: "path is defined"
    fail_msg: 'The variable "path" must be defined.'
  register: 'assert_file_content__path_defined_assertion'

- name: "Assert that match variable is defined"
  assert:
    that: "match is defined"
    fail_msg: 'The variable "match" must be defined.'
  register: 'assert_file_content__match_defined_assertion'

- name: 'Get {{ path }} content'
  slurp:
    path: '{{ path }}'
  register: 'assert_file_content__file'

- name: 'Assert {{ path }} content match {{ match }}'
  assert:
    that: '(assert_file_content__file.content | b64decode) is regex(match, multiline=multiline, ignorecase=ignorecase)'
    fail_msg: '{{ path }} content does not match "{{ match }}" (multi-line={{ multiline }}, ignore-case={{ ignorecase }}).'
  register: 'assert_file_content__match_assertion'
